#!/bin/bash -e

echo "Please consider ./iiab-install instead of the lesser-supported ./runansible"

PLAYBOOK="iiab.yml"
INVENTORY="ansible_hosts"

ansible -m setup -i $INVENTORY localhost --connection=local >> /dev/null

ansible-playbook -i $INVENTORY $PLAYBOOK --connection=local
